/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq.tables.records;


import de.jottyfan.auto.db.jooq.enums.EnumFuel;
import de.jottyfan.auto.db.jooq.enums.EnumProvider;
import de.jottyfan.auto.db.jooq.tables.TMileage;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMileageRecord extends TableRecordImpl<TMileageRecord> implements Record9<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, String> {

    private static final long serialVersionUID = -602798333;

    /**
     * Setter for <code>ddgj1773.t_mileage.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.mileage</code>.
     */
    public void setMileage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.mileage</code>.
     */
    public Integer getMileage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.fuel</code>.
     */
    public void setFuel(EnumFuel value) {
        set(2, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.fuel</code>.
     */
    public EnumFuel getFuel() {
        return (EnumFuel) get(2);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.price</code>. in €
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.price</code>. in €
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.amount</code>. in l
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.amount</code>. in l
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.provider</code>.
     */
    public void setProvider(EnumProvider value) {
        set(6, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.provider</code>.
     */
    public EnumProvider getProvider() {
        return (EnumProvider) get(6);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.buydate</code>.
     */
    public void setBuydate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.buydate</code>.
     */
    public Timestamp getBuydate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ddgj1773.t_mileage.annotation</code>.
     */
    public void setAnnotation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ddgj1773.t_mileage.annotation</code>.
     */
    public String getAnnotation() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TMileage.T_MILEAGE.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TMileage.T_MILEAGE.MILEAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumFuel> field3() {
        return TMileage.T_MILEAGE.FUEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TMileage.T_MILEAGE.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return TMileage.T_MILEAGE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TMileage.T_MILEAGE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumProvider> field7() {
        return TMileage.T_MILEAGE.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TMileage.T_MILEAGE.BUYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TMileage.T_MILEAGE.ANNOTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMileage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFuel component3() {
        return getFuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumProvider component7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAnnotation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMileage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFuel value3() {
        return getFuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumProvider value7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAnnotation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value2(Integer value) {
        setMileage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value3(EnumFuel value) {
        setFuel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value7(EnumProvider value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value8(Timestamp value) {
        setBuydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord value9(String value) {
        setAnnotation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMileageRecord values(Integer value1, Integer value2, EnumFuel value3, String value4, BigDecimal value5, BigDecimal value6, EnumProvider value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TMileageRecord
     */
    public TMileageRecord() {
        super(TMileage.T_MILEAGE);
    }

    /**
     * Create a detached, initialised TMileageRecord
     */
    public TMileageRecord(Integer pk, Integer mileage, EnumFuel fuel, String location, BigDecimal price, BigDecimal amount, EnumProvider provider, Timestamp buydate, String annotation) {
        super(TMileage.T_MILEAGE);

        set(0, pk);
        set(1, mileage);
        set(2, fuel);
        set(3, location);
        set(4, price);
        set(5, amount);
        set(6, provider);
        set(7, buydate);
        set(8, annotation);
    }
}
