/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq.tables.records;


import de.jottyfan.auto.db.jooq.tables.VLogin;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VLoginRecord extends TableRecordImpl<VLoginRecord> implements Record1<String> {

    private static final long serialVersionUID = -1733566302;

    /**
     * Setter for <code>ddgj1773.v_login.password</code>.
     */
    public void setPassword(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ddgj1773.v_login.password</code>.
     */
    public String getPassword() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VLogin.V_LOGIN.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VLoginRecord value1(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VLoginRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLoginRecord
     */
    public VLoginRecord() {
        super(VLogin.V_LOGIN);
    }

    /**
     * Create a detached, initialised VLoginRecord
     */
    public VLoginRecord(String password) {
        super(VLogin.V_LOGIN);

        set(0, password);
    }
}
