/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq.tables.records;


import de.jottyfan.auto.db.jooq.enums.EnumFuel;
import de.jottyfan.auto.db.jooq.enums.EnumProvider;
import de.jottyfan.auto.db.jooq.tables.VMileage;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMileageRecord extends TableRecordImpl<VMileageRecord> implements Record10<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, BigDecimal, String> {

    private static final long serialVersionUID = 370836149;

    /**
     * Setter for <code>ddgj1773.v_mileage.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.mileage</code>.
     */
    public void setMileage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.mileage</code>.
     */
    public Integer getMileage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.fuel</code>.
     */
    public void setFuel(EnumFuel value) {
        set(2, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.fuel</code>.
     */
    public EnumFuel getFuel() {
        return (EnumFuel) get(2);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.provider</code>.
     */
    public void setProvider(EnumProvider value) {
        set(6, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.provider</code>.
     */
    public EnumProvider getProvider() {
        return (EnumProvider) get(6);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.buydate</code>.
     */
    public void setBuydate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.buydate</code>.
     */
    public Timestamp getBuydate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.€/l</code>.
     */
    public void set€_2fl(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.€/l</code>.
     */
    public BigDecimal get€_2fl() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>ddgj1773.v_mileage.annotation</code>.
     */
    public void setAnnotation(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ddgj1773.v_mileage.annotation</code>.
     */
    public String getAnnotation() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, BigDecimal, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, EnumFuel, String, BigDecimal, BigDecimal, EnumProvider, Timestamp, BigDecimal, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VMileage.V_MILEAGE.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VMileage.V_MILEAGE.MILEAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumFuel> field3() {
        return VMileage.V_MILEAGE.FUEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VMileage.V_MILEAGE.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return VMileage.V_MILEAGE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return VMileage.V_MILEAGE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumProvider> field7() {
        return VMileage.V_MILEAGE.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VMileage.V_MILEAGE.BUYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return de.jottyfan.auto.db.jooq.tables.VMileage.V_MILEAGE.€_2fL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VMileage.V_MILEAGE.ANNOTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMileage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFuel component3() {
        return getFuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumProvider component7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return get€_2fl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAnnotation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMileage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFuel value3() {
        return getFuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumProvider value7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return get€_2fl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAnnotation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value2(Integer value) {
        setMileage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value3(EnumFuel value) {
        setFuel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value7(EnumProvider value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value8(Timestamp value) {
        setBuydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value9(BigDecimal value) {
        set€_2fl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord value10(String value) {
        setAnnotation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileageRecord values(Integer value1, Integer value2, EnumFuel value3, String value4, BigDecimal value5, BigDecimal value6, EnumProvider value7, Timestamp value8, BigDecimal value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VMileageRecord
     */
    public VMileageRecord() {
        super(VMileage.V_MILEAGE);
    }

    /**
     * Create a detached, initialised VMileageRecord
     */
    public VMileageRecord(Integer pk, Integer mileage, EnumFuel fuel, String location, BigDecimal price, BigDecimal amount, EnumProvider provider, Timestamp buydate, BigDecimal €_2fl, String annotation) {
        super(VMileage.V_MILEAGE);

        set(0, pk);
        set(1, mileage);
        set(2, fuel);
        set(3, location);
        set(4, price);
        set(5, amount);
        set(6, provider);
        set(7, buydate);
        set(8, €_2fl);
        set(9, annotation);
    }
}
