/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq.tables;


import de.jottyfan.auto.db.jooq.Ddgj1773;
import de.jottyfan.auto.db.jooq.enums.EnumFuel;
import de.jottyfan.auto.db.jooq.enums.EnumProvider;
import de.jottyfan.auto.db.jooq.tables.records.VMileageRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMileage extends TableImpl<VMileageRecord> {

    private static final long serialVersionUID = 1345971247;

    /**
     * The reference instance of <code>ddgj1773.v_mileage</code>
     */
    public static final VMileage V_MILEAGE = new VMileage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VMileageRecord> getRecordType() {
        return VMileageRecord.class;
    }

    /**
     * The column <code>ddgj1773.v_mileage.pk</code>.
     */
    public final TableField<VMileageRecord, Integer> PK = createField("pk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ddgj1773.v_mileage.mileage</code>.
     */
    public final TableField<VMileageRecord, Integer> MILEAGE = createField("mileage", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ddgj1773.v_mileage.fuel</code>.
     */
    public final TableField<VMileageRecord, EnumFuel> FUEL = createField("fuel", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(de.jottyfan.auto.db.jooq.enums.EnumFuel.class), this, "");

    /**
     * The column <code>ddgj1773.v_mileage.location</code>.
     */
    public final TableField<VMileageRecord, String> LOCATION = createField("location", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ddgj1773.v_mileage.price</code>.
     */
    public final TableField<VMileageRecord, BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>ddgj1773.v_mileage.amount</code>.
     */
    public final TableField<VMileageRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>ddgj1773.v_mileage.provider</code>.
     */
    public final TableField<VMileageRecord, EnumProvider> PROVIDER = createField("provider", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(de.jottyfan.auto.db.jooq.enums.EnumProvider.class), this, "");

    /**
     * The column <code>ddgj1773.v_mileage.buydate</code>.
     */
    public final TableField<VMileageRecord, Timestamp> BUYDATE = createField("buydate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ddgj1773.v_mileage.€/l</code>.
     */
    public final TableField<VMileageRecord, BigDecimal> €_2fL = createField("€/l", org.jooq.impl.SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>ddgj1773.v_mileage.annotation</code>.
     */
    public final TableField<VMileageRecord, String> ANNOTATION = createField("annotation", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>ddgj1773.v_mileage</code> table reference
     */
    public VMileage() {
        this(DSL.name("v_mileage"), null);
    }

    /**
     * Create an aliased <code>ddgj1773.v_mileage</code> table reference
     */
    public VMileage(String alias) {
        this(DSL.name(alias), V_MILEAGE);
    }

    /**
     * Create an aliased <code>ddgj1773.v_mileage</code> table reference
     */
    public VMileage(Name alias) {
        this(alias, V_MILEAGE);
    }

    private VMileage(Name alias, Table<VMileageRecord> aliased) {
        this(alias, aliased, null);
    }

    private VMileage(Name alias, Table<VMileageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ddgj1773.DDGJ1773;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileage as(String alias) {
        return new VMileage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMileage as(Name alias) {
        return new VMileage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VMileage rename(String name) {
        return new VMileage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VMileage rename(Name name) {
        return new VMileage(name, null);
    }
}
