/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq.enums;


import de.jottyfan.auto.db.jooq.Ddgj1773;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EnumFuel implements EnumType {

    E10("E10"),

    Natural95("Natural95"),

    Super("Super");

    private final String literal;

    private EnumFuel(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ddgj1773.DDGJ1773;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "enum_fuel";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
