/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq;


import de.jottyfan.auto.db.jooq.tables.TMileage;
import de.jottyfan.auto.db.jooq.tables.VLogin;
import de.jottyfan.auto.db.jooq.tables.VMileage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ddgj1773 extends SchemaImpl {

    private static final long serialVersionUID = 748276929;

    /**
     * The reference instance of <code>ddgj1773</code>
     */
    public static final Ddgj1773 DDGJ1773 = new Ddgj1773();

    /**
     * The table <code>ddgj1773.t_mileage</code>.
     */
    public final TMileage T_MILEAGE = de.jottyfan.auto.db.jooq.tables.TMileage.T_MILEAGE;

    /**
     * The table <code>ddgj1773.v_login</code>.
     */
    public final VLogin V_LOGIN = de.jottyfan.auto.db.jooq.tables.VLogin.V_LOGIN;

    /**
     * The table <code>ddgj1773.v_mileage</code>.
     */
    public final VMileage V_MILEAGE = de.jottyfan.auto.db.jooq.tables.VMileage.V_MILEAGE;

    /**
     * No further instances allowed
     */
    private Ddgj1773() {
        super("ddgj1773", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TMileage.T_MILEAGE,
            VLogin.V_LOGIN,
            VMileage.V_MILEAGE);
    }
}
