/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.auto.db.jooq;


import de.jottyfan.auto.db.jooq.tables.TMileage;
import de.jottyfan.auto.db.jooq.tables.VLogin;
import de.jottyfan.auto.db.jooq.tables.VMileage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ddgj1773
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ddgj1773.t_mileage</code>.
     */
    public static final TMileage T_MILEAGE = de.jottyfan.auto.db.jooq.tables.TMileage.T_MILEAGE;

    /**
     * The table <code>ddgj1773.v_login</code>.
     */
    public static final VLogin V_LOGIN = de.jottyfan.auto.db.jooq.tables.VLogin.V_LOGIN;

    /**
     * The table <code>ddgj1773.v_mileage</code>.
     */
    public static final VMileage V_MILEAGE = de.jottyfan.auto.db.jooq.tables.VMileage.V_MILEAGE;
}
